name: sign_language_app
description: "A professional Sign Language Data Collection and Inference App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core utilities
  path_provider: ^2.1.2
  intl: ^0.19.0
  
  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon_source.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/vocabulary.json
